name: Terraform Validation

on: push

jobs:
  lambda-lint:
    name: Lambda Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: yarn install
        working-directory: lambda
      - run: yarn lint
        working-directory: lambda

  terraform-lint:
    name: Terraform lint
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Terraform lint'
        uses: notrenderfarm/tflint-action@v1.2
        with:
          directory: '.'